import { z } from "zod";
import { Context } from "../context";
import { Session } from "../session";

export abstract class Tool<ISchema extends z.ZodType, O> {
  static readonly name: string;
  abstract description: string;
  abstract inputSchema: ISchema;
  // input is the parameters for the tool, which is expected to be generated by the AI agent
  abstract handler: (
    context: Context,
    session: Session,
    input: z.infer<ISchema>,
  ) => Promise<O>;
}
