import { z } from "zod";
import { Result, ok, err } from "neverthrow";
import { Context } from "../context";

export { ok, err };

export abstract class Tool<ISchema extends z.ZodType, O, E = string> {
  static readonly toolName: string;
  abstract description: string;
  abstract inputSchema: ISchema;
  // input is the parameters for the tool, which is expected to be generated by the AI agent
  abstract handler: (
    context: Context,
    agentId: string,
    input: z.infer<ISchema>,
  ) => Promise<Result<O, E>>;
}
